project:
  type: website

website:
  title: "GH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - EDA.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: true    



